omp1: omp_bug1.c
	gcc -o omp1.exe omp_bug1.c -fopenmp
	@ ./omp1.exe
omp2: omp_bug2.c
	gcc -o omp2.exe omp_bug2.c -fopenmp
	@ ./omp2.exe
omp3: omp_bug3.c
	gcc -o omp3.exe omp_bug3.c -fopenmp
	@ ./omp3.exe
omp4: omp_bug4.c
	gcc -o omp4.exe omp_bug4.c -fopenmp
	@ ./omp4.sh
omp5: omp_bug5.c
	gcc -o omp5.exe omp_bug5.c -fopenmp
	@ ./omp5.exe
omp6: omp_bug6.c
	gcc -o omp6.exe omp_bug6.c -fopenmp
	@ ./omp6.exe
mpi1: mpi_bug1.c
	gcc -o mpi1.exe mpi_bug1.c 
	@ ./mpi1.exe
mpi2: mpi_bug2.c
	gcc -o mpi2.exe mpi_bug2.c 
	@ ./mpi2.exe
mpi3: mpi_bug3.c
	gcc -o mpi3.exe mpi_bug3.c 
	@ ./mpi3.exe
mpi4: mpi_bug4.c
	gcc -o mpi4.exe mpi_bug4.c 
	@ ./mpi4.exe
mpi5: mpi_bug5.c
	gcc -o mpi5.exe mpi_bug5.c 
	@ ./mpi5.exe
mpi6: mpi_bug6.c
	gcc -o mpi6.exe mpi_bug6.c 
	@ ./mpi6.exe